import streamlit as str
import yfinance as yf
import pandas as pd
import pandas_ta as ta  # The new quantitative library
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from datetime import datetime
import time

# Page config
str.set_page_config(page_title="QuantEdge Predictive Engine", layout="wide")

# ==========================================
# 1. INITIALIZE ADVANCED PERSISTENT MEMORY
# ==========================================
if "cash" not in str.session_state:
    str.session_state.cash = 10000.00  
if "portfolio" not in str.session_state:
    str.session_state.portfolio = {}   
if "statement" not in str.session_state:
    str.session_state.statement = []   
if "engine_executed" not in str.session_state:
    str.session_state.engine_executed = False
if "current_market_data" not in str.session_state:
    str.session_state.current_market_data = None
if "last_analyzed_ticker" not in str.session_state:
    str.session_state.last_analyzed_ticker = None
if "live_price" not in str.session_state:
    str.session_state.live_price = 0.0

ASSET_CLASSES = {
    "Equities": {"Apple": "AAPL", "Tesla": "TSLA", "Nvidia": "NVDA", "S&P 500": "SPY"},
    "Crypto": {"Bitcoin": "BTC-USD", "Ethereum": "ETH-USD", "Solana": "SOL-USD"},
    "Forex": {"EUR/USD": "EURUSD=X", "GBP/USD": "GBPUSD=X", "USD/JPY": "JPY=X"},
    "Commodities": {"Gold": "GC=F", "Crude Oil": "CL=F"}
}

# ==========================================
# 2. CONTROLS & AUTO-PILOT
# ==========================================
str.sidebar.header("🕹️ Terminal Controls")

def reset_engine():
    str.session_state.engine_executed = False

asset_type = str.sidebar.selectbox("Asset Class", list(ASSET_CLASSES.keys()), on_change=reset_engine)
asset_name = str.sidebar.selectbox("Select Ticker", list(ASSET_CLASSES[asset_type].keys()), on_change=reset_engine)
ticker = ASSET_CLASSES[asset_type][asset_name]

timeframe = str.sidebar.selectbox("Interval", ["1 Minute", "5 Minutes", "15 Minutes", "1 Hour"], on_change=reset_engine)
chart_style = str.sidebar.radio("Chart Style", ["Candlestick", "Line Chart"])

str.sidebar.divider()
str.sidebar.header("⚡ Live Auto-Pilot")
auto_refresh = str.sidebar.toggle("Enable Fast-Sync Loop", value=False)
refresh_rate = str.sidebar.slider("Refresh Interval (Sec)", 5, 60, 5)

interval_mapping = {
    "1 Minute": {"int": "1m", "period": "1d"},
    "5 Minutes": {"int": "5m", "period": "5d"},
    "15 Minutes": {"int": "15m", "period": "5d"},
    "1 Hour": {"int": "1h", "period": "60d"}
}

# ==========================================
# 3. HEAVYWEIGHT QUANTITATIVE DATA PULL
# ==========================================
execute_clicked = str.sidebar.button("🔄 Force Data Sync", use_container_width=True)

if execute_clicked or auto_refresh or not str.session_state.engine_executed:
    chosen_int = interval_mapping[timeframe]["int"]
    chosen_per = interval_mapping[timeframe]["period"]
    
    df = yf.download(ticker, period=chosen_per, interval=chosen_int, progress=False)
    
    if df is not None and not df.empty:
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)
        df.reset_index(inplace=True)
        
        # --- MULTI-TOOL INDICATOR SUITE (pandas-ta) ---
        df.ta.ema(length=9, append=True)  # Fast Trend
        df.ta.ema(length=21, append=True) # Slow Trend
        df.ta.rsi(length=14, append=True) # Momentum
        df.ta.macd(fast=12, slow=26, signal=9, append=True) # Velocity
        df.ta.bbands(length=20, std=2, append=True) # Volatility/Standard Deviation
        df.ta.stoch(k=14, d=3, smooth_k=3, append=True) # Overbought/Oversold
        df.ta.atr(length=14, append=True) # True Range for Risk
        
        # Clean NaN values generated by moving averages
        df.fillna(method='bfill', inplace=True)
        
        str.session_state.live_price = float(df['Close'].iloc[-1])
        str.session_state.current_market_data = df
        str.session_state.engine_executed = True
        str.session_state.last_analyzed_ticker = ticker
        
        # Auto-Liquidation Checks
        if ticker in str.session_state.portfolio:
            pos = str.session_state.portfolio[ticker]
            trigger = None
            if pos['tp'] > 0 and str.session_state.live_price >= pos['tp']: trigger = "TAKE PROFIT"
            elif pos['sl'] > 0 and str.session_state.live_price <= pos['sl']: trigger = "STOP LOSS"
                
            if trigger:
                revenue = pos['qty'] * str.session_state.live_price
                str.session_state.cash += revenue
                str.session_state.statement.append({
                    "Time": datetime.now().strftime("%H:%M:%S"), "Asset": ticker, "Action": f"AUTO-SELL ({trigger})",
                    "Qty": pos['qty'], "Price": str.session_state.live_price, "Total Value": revenue
                })
                del str.session_state.portfolio[ticker]
                str.toast(f"{trigger} HIT! Auto-Sold {ticker}", icon="🔥")

# ==========================================
# 4. PREDICTIVE FORECAST & UI
# ==========================================
tab1, tab2 = str.tabs(["🔮 Predictive Terminal", "💼 Portfolio Ledger"])

with tab1:
    if str.session_state.engine_executed and str.session_state.current_market_data is not None:
        df = str.session_state.current_market_data
        curr_p = str.session_state.live_price
        active_ticker = str.session_state.last_analyzed_ticker
        latest = df.iloc[-1]
        
        str.title(f"🔮 Predictive Forecast: {asset_name}")
        
        # --- THE PREDICTIVE CONSENSUS ALGORITHM ---
        score = 0
        max_score = 6 # Total number of conditions evaluated
        
        # Extract variables safely
        ema9 = latest.get('EMA_9', curr_p)
        ema21 = latest.get('EMA_21', curr_p)
        rsi = latest.get('RSI_14', 50.0)
        macd = latest.get('MACD_12_26_9', 0.0)
        macds = latest.get('MACDs_12_26_9', 0.0)
        stoch_k = latest.get('STOCHk_14_3_3', 50.0)
        stoch_d = latest.get('STOCHd_14_3_3', 50.0)
        bb_upper = latest.get('BBU_20_2.0', curr_p * 1.01)
        bb_lower = latest.get('BBL_20_2.0', curr_p * 0.99)
        atr = latest.get('ATRr_14', curr_p * 0.01)

        # Evaluate Bullish vs Bearish Weights
        if ema9 > ema21: score += 1
        else: score -= 1
            
        if rsi < 35: score += 1.5 # Strong oversold buy
        elif rsi > 65: score -= 1.5 # Strong overbought sell
        elif ema9 > ema21 and rsi > 50: score += 0.5 # Trend continuation
            
        if macd > macds: score += 1
        else: score -= 1
            
        if stoch_k > stoch_d and stoch_k < 80: score += 1
        elif stoch_k < stoch_d and stoch_k > 20: score -= 1
            
        if curr_p > ema21: score += 1
        else: score -= 1
        
        # Calculate Confidence & Forecast Logic
        raw_confidence = abs(score) / max_score
        confidence_pct = min(raw_confidence * 100, 99.9) # Cap at 99.9% because nothing is 100%
        
        if score >= 2:
            verdict = "BULLISH (UPWARD FORECAST) 🟢"
            # Project pull-back entry and breakout exit
            proj_entry = ema9 # Buy if it pulls back to the fast moving average
            proj_exit = bb_upper + (atr * 0.5) # Exit at the upper band + volatility push
            proj_sl = bb_lower - (atr * 0.5)
        elif score <= -2:
            verdict = "BEARISH (DOWNWARD FORECAST) 🔴"
            proj_entry = ema21 # Short/Sell at the slow moving average
            proj_exit = bb_lower - (atr * 0.5)
            proj_sl = bb_upper + (atr * 0.5)
        else:
            verdict = "CONSOLIDATION (NEUTRAL) ⚪"
            proj_entry = curr_p
            proj_exit = bb_upper
            proj_sl = bb_lower
            confidence_pct = 50.0

        # --- UI DISPLAY: FORECAST MATRIX ---
        str.markdown("### 🤖 Institutional Forecast Engine")
        v_col1, v_col2, v_col3 = str.columns(3)
        v_col1.metric("Predicted Direction", verdict)
        v_col2.metric("Algorithmic Confidence", f"{confidence_pct:.1f}%")
        v_col3.metric("Current Live Price", f"${curr_p:,.4f}")
        
        str.info(f"**Engine Recommendation:** Look for a predictive **Entry near ${proj_entry:,.2f}**. Set your primary **Exit Target at ${proj_exit:,.2f}**, with a hard statistical **Stop-Loss around ${proj_sl:,.2f}**.")

        # --- DYNAMIC CHARTING ---
        fig = make_subplots(rows=3, cols=1, shared_xaxes=True, vertical_spacing=0.03, row_heights=[0.6, 0.2, 0.2])
        time_col = df['Datetime'] if 'Datetime' in df else df['Date']
        
        if chart_style == "Candlestick":
            fig.add_trace(go.Candlestick(x=time_col, open=df['Open'], high=df['High'], low=df['Low'], close=df['Close'], name="Price"), row=1, col=1)
        else:
            fig.add_trace(go.Scatter(x=time_col, y=df['Close'], name="Price", line=dict(color='cyan', width=2)), row=1, col=1)
            
        # Draw Bollinger Bands and EMAs
        fig.add_trace(go.Scatter(x=time_col, y=df['BBU_20_2.0'], line=dict(color='gray', width=1, dash='dot'), name="Upper Band"), row=1, col=1)
        fig.add_trace(go.Scatter(x=time_col, y=df['BBL_20_2.0'], line=dict(color='gray', width=1, dash='dot'), fill='tonexty', fillcolor='rgba(128,128,128,0.1)', name="Lower Band"), row=1, col=1)
        fig.add_trace(go.Scatter(x=time_col, y=df['EMA_9'], line=dict(color='yellow', width=1.5), name="EMA 9"), row=1, col=1)
        fig.add_trace(go.Scatter(x=time_col, y=df['EMA_21'], line=dict(color='fuchsia', width=1.5), name="EMA 21"), row=1, col=1)
        
        # Subplot 2: RSI
        fig.add_trace(go.Scatter(x=time_col, y=df['RSI_14'], line=dict(color='orange'), name="RSI"), row=2, col=1)
        fig.add_hline(y=70, line_dash="dash", line_color="red", row=2, col=1)
        fig.add_hline(y=30, line_dash="dash", line_color="green", row=2, col=1)
        
        # Subplot 3: MACD Histogram
        fig.add_trace(go.Bar(x=time_col, y=df['MACDh_12_26_9'], marker_color='blue', name="MACD Hist"), row=3, col=1)

        fig.update_layout(xaxis_rangeslider_visible=False, height=650, template="plotly_dark", margin=dict(t=10, b=10))
        str.plotly_chart(fig, use_container_width=True)

        # --- ZERO-LAG MANUAL EXECUTION FORM ---
        str.markdown("### 💼 Execute Projected Trade")
        str.write(f"**Purchasing Power:** `${str.session_state.cash:,.2f}`")
        
        with str.form("trade_form"):
            t_col1, t_col2, t_col3 = str.columns(3)
            t_qty = t_col1.number_input("Quantity", min_value=0.01, max_value=1000.0, value=1.00, step=0.1)
            # Default to the projected algorithm exits
            tp_price = t_col2.number_input("Take Profit Target ($)", value=float(proj_exit), step=0.01)
            sl_price = t_col3.number_input("Stop Loss Target ($)", value=float(proj_sl), step=0.01)
            
            b_col1, b_col2 = str.columns(2)
            buy_intent = b_col1.form_submit_button("🟢 Buy Market", use_container_width=True)
            sell_intent = b_col2.form_submit_button("🔴 Sell Position", use_container_width=True)

        if buy_intent:
            cost = t_qty * curr_p
            if str.session_state.cash >= cost:
                str.session_state.cash -= cost
                if active_ticker in str.session_state.portfolio:
                    old_qty = str.session_state.portfolio[active_ticker].get('qty', 0)
                    old_avg = str.session_state.portfolio[active_ticker].get('avg_entry', 0)
                    new_qty = old_qty + t_qty
                    new_avg = ((old_qty * old_avg) + (t_qty * curr_p)) / new_qty
                    str.session_state.portfolio[active_ticker] = {'qty': new_qty, 'avg_entry': new_avg, 'tp': tp_price, 'sl': sl_price}
                else:
                    str.session_state.portfolio[active_ticker] = {'qty': t_qty, 'avg_entry': curr_p, 'tp': tp_price, 'sl': sl_price}
                str.session_state.statement.append({"Time": datetime.now().strftime("%H:%M:%S"), "Asset": active_ticker, "Action": "BUY", "Qty": t_qty, "Price": curr_p, "Total Value": cost})
                str.success(f"Executed BUY at ${curr_p:.2f}")
                time.sleep(0.5)
                str.rerun()
            else: str.error("Insufficient Capital.")

        if sell_intent:
            if active_ticker in str.session_state.portfolio and str.session_state.portfolio[active_ticker].get('qty', 0) >= t_qty:
                revenue = t_qty * curr_p
                str.session_state.cash += revenue
                str.session_state.portfolio[active_ticker]['qty'] -= t_qty
                if str.session_state.portfolio[active_ticker]['qty'] <= 0: del str.session_state.portfolio[active_ticker]
                str.session_state.statement.append({"Time": datetime.now().strftime("%H:%M:%S"), "Asset": active_ticker, "Action": "SELL", "Qty": t_qty, "Price": curr_p, "Total Value": revenue})
                str.success(f"Executed SELL at ${curr_p:.2f}")
                time.sleep(0.5)
                str.rerun()
            else: str.error("Not enough units.")
    else:
        str.info("Waiting for market data connection...")

# ==========================================
# 5. PORTFOLIO LEDGER
# ==========================================
with tab2:
    str.header("📈 Active Risk Ledger")
    str.metric("Liquid Cash Balance", f"${str.session_state.cash:,.2f}")
    
    if str.session_state.portfolio:
        str.subheader("Open Positions")
        p_data = []
        for port_t, d in str.session_state.portfolio.items():
            if not isinstance(d, dict): d = {'qty': float(d), 'avg_entry': 0.0, 'tp': 0.0, 'sl': 0.0}
            lp = str.session_state.live_price if port_t == str.session_state.last_analyzed_ticker else d.get('avg_entry', 0.0)
            p_data.append({
                "Asset": port_t, "Units": d.get('qty', 0), "Entry": f"${d.get('avg_entry', 0):,.2f}",
                "TP": f"${d.get('tp', 0):,.2f}", "SL": f"${d.get('sl', 0):,.2f}", "Live P&L": f"${(lp - d.get('avg_entry', 0)) * d.get('qty', 0):,.2f}"
            })
        str.dataframe(pd.DataFrame(p_data), use_container_width=True)
    else: str.info("No open positions.")
        
    if str.session_state.statement:
        str.subheader("Execution History")
        str.dataframe(pd.DataFrame(str.session_state.statement).iloc[::-1], use_container_width=True)

if auto_refresh:
    time.sleep(refresh_rate)
    str.rerun()
